### ISSUE TITLE
Swift class with two words separated by "." breaks Frida logic

### ISSUE THREAD

**Issue by oleavr** [frida/frida-objc#1]
Continuation of frida/frida#228. As explained by @hduarte:

The app is developed in swift. When I try to obtain the methods of the classes, frida breaks when the class is composed by 2 names separated by a "." For example:

...
[+] Class: App1.TransactionListPickerViewController
TypeError: cannot read property 'TransactionListPickerViewControl...' of undefined

Any ideias of how to show frida that the classname is "App1.TransactionListPickerViewController" and not just "App1" ?

**Comment by oleavr** [comment]
@hduarte Could you include some code explaining what exactly you're trying when the above exception is thrown?

**Comment by hduarte** [comment]
@oleavr This is the code I'm using:

console.log("[*] Started: Find Methods")
if (ObjC.available)
{
    for (var className in ObjC.classes)
    {
        if (ObjC.classes.hasOwnProperty(className))
        {
            console.log("[+] Class: " + className);
            var methods = eval('ObjC.classes.' + className + '.$ownMethods');
            for (var i = 0; i < methods.length; i++)
            {
                console.log("\t[-] Method: "+methods[i]);
            }
        }
    }
}
else
{
    console.log("Objective-C Runtime is not available!");
}
console.log("[*] Completed: Find Methods")

**Comment by hduarte** [comment]
I'm connecting to the app via usb using frida console.

**Comment by oleavr** [comment]
Ah! This is not a bug in Frida – that code is doing the wrong thing there using `eval()`. Instead just use: `ObjC.classes[className].$ownMethods`.

**Comment by hduarte** [comment]
Thks for the help @oleavr.

Is there a similar way to obtain the classes created in the app and not the inherited ones from iOS, the same way there is ownMethods for non inherited methods  ?

**Comment by oleavr** [comment]
Not currently, but you can implement it yourself by looking at each class' first own method's `implementation`, and comparing that address to `Process.enumerateRanges()`.

**Comment by hduarte** [comment]
Thks @oleavr I'll investigate that.
