### ISSUE TITLE
Failed to handle ObjC++ instance method with C++ structure

### ISSUE THREAD

**Issue by BlueCocoa** [frida/frida-objc#4]
With class-dump, I get an ObjC++ class named ```QQMessageRevokeEngine```, and there is an instance method ```-[QQMessageRevokeEngine handleRecallNotify:(struct RecallModel *)arg1 isOnline:(BOOL)arg2]```

However, when using Frida to retrieve this method, error occurs.

```
[Local::ProcName::QQ]-> var m = ObjC.classes.QQMessageRevokeEngine["- handleReca
llNotify:isOnline:"]
Error: Unable to handle type )
```

The signature of that method is
```
handleRecallNotify:isOnline:","v28@0:8^{RecallModel=^^?iB{vector<msg_recall::RecallItem *, std::__1::allocator<msg_recall::RecallItem *> >=^^{RecallItem}^^{RecallItem}{__compressed_pair<msg_recall::RecallItem **, std::__1::allocator<msg_recall::RecallItem *> >=^^{RecallItem}}}BQ(?=QQ)}1…"
```

It seems that there may be an issue in frida-objc while handle instance method with C++ structure.

**Comment by BlueCocoa** [comment]
btw, the structure, RecallModel, parsed by class-dump is

```
struct RecallModel {
    CDUnknownFunctionPointerType *_field1;
    int _field2;
    _Bool _field3;
    struct vector<msg_recall::RecallItem *, std::__1::allocator<msg_recall::RecallItem *>> _field4;
    _Bool _field5;
    unsigned long long _field6;
    union {
        unsigned long long _field1;
        unsigned long long _field2;
    } _field7;
};
```

**Comment by oleavr** [comment]
Thanks for reporting. This is definitely a bug in frida-objc. Parsing code is [here](https://github.com/frida/frida-objc/blob/2e80ab81fe320b3ad06ca0ecdd1dee1a28544aa8/index.js#L1940-L1994) in case you're interested in taking a stab at it.

Cheers!
